Booking.destroy_all
Question.destroy_all
Activity.destroy_all
User.destroy_all
Answer.destroy_all

q5 = Question.create(title: "Do you like music?", choice_1: 555, choice_2: 666, button_1: "I hate French rap", button_2: "Je suis en rapper du la France")
q4 = Question.create(title: "Alchool or culture?", choice_1: q5.id, choice_2: 444, button_1: "CnH(2n + 1)OH please", button_2: "Culture please")
q3 = Question.create(title: "Fun or Food?", choice_1: q4.id, choice_2: 999, button_1: "I wanna get some fun", button_2: "FOOD WHERE IS FOOOOOOD????")
q2 = Question.create(title: "Are you a day-sparkler?", choice_1: q3.id, choice_2: q3.id, button_1: "Oh yea, definitely", button_2: "Da fuq you talkin' 'bout?")
q1 = Question.create(title: "Do you like to hang out alone or with other human beigns?", choice_1: q2.id, choice_2: 888, button_1: "The world is wrong", button_2: "I'm a beigns")


l1 = Activity.create(title: "Victoria & Albert Museum", description: "The Victoria and Albert Museum (often abbreviated as the V&A) in London is the world's largest museum of applied and decorative arts and design, as well as sculpture, housing a permanent collection of over 2.27 million objects. It was founded in 1852 and titled after Queen Victoria and Prince Albert.", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/V%26A_Museum_Foyer%2C_London_-_Oct_2012.jpg/800px-V%26A_Museum_Foyer%2C_London_-_Oct_2012.jpg", url: "https://www.vam.ac.uk/visit", category: "Museum" )
l2 = Activity.create(title: "Science Museum", category: "Museum", description: "The Science Museum is a major museum on Exhibition Road in South Kensington, London. It was founded in 1857 and today is one of the city's major tourist attractions, attracting 3.3 million visitors annually.", image: "https://upload.wikimedia.org/wikipedia/commons/c/c9/Science_Museum_-_East_Hall_2390.jpg", url: "https://www.sciencemuseum.org.uk/visit-us")
l3 = Activity.create(title: "National History Museum", description: "Wander through the spectacular halls of the Natural History Museum, as you discover fascinating exhibits from the natural world. Marvel at dinosaur skeletons or gawp at a giant blue whale model.", category: "Museum", image: "http://www.nhm.ac.uk/content/dam/nhmwww/visit/waterhouse-facade-two-column.jpg", url: "http://www.nhm.ac.uk/visit/getting-here.html")
l4 = Activity.create(title: "National Gallery", description: "The Gallery is an exempt charity, and a non-departmental public body of the Department for Culture, Media and Sport.[3] Its collection belongs to the government on behalf of the British public, and entry to the main collection is free of charge. It is among the most visited art museums in the world, after the Louvre, the British Museum, and the Metropolitan Museum of Art.", category: "Culture", image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Galer%C3%ADa_Nacional%2C_Londres%2C_Inglaterra%2C_2014-08-07%2C_DD_035.JPG/1280px-Galer%C3%ADa_Nacional%2C_Londres%2C_Inglaterra%2C_2014-08-07%2C_DD_035.JPG", url: "https://www.nationalgallery.org.uk/")
l5 = Activity.create(title: "Imperial War Museum", description: "IWM London is the world’s leading museum of war. Founded during the First World War, it gives voice to the extraordinary experiences of ordinary people forced to live their lives in a world torn apart by conflict.", category: "Museum", image: "https://cdn.londonandpartners.com/assets/attractions/culture/40814-640x360-imperialwarmuseum_front_640.jpg", url: "https://www.iwm.org.uk/visits/iwm-london")
l6 = Activity.create(title: "National Maritime Museum", description: "Set in historic Maritime Greenwich, the National Maritime Museum showcases Britain’s naval history, from sea battles to exploratory expeditions. See ancient maps and ship models, and don’t miss the iconic uniform Nelson wore the day of the Battle of Trafalgar. ", category: "Museum", image: "https://upload.wikimedia.org/wikipedia/commons/1/18/National_maritime_museum.jpg", url: "https://www.rmg.co.uk/")
l7 = Activity.create(title: "Core by Clare Smyth", description: "Core is an elegant and informal fine dining restaurant with an emphasis on natural, sustainable food, sourced from the UK’s most dedicated farmers and food producers. Micheline guide gave 2 out of 3 stars to Core by Claire Smyth", category: "Restaurant", image: "https://www.corebyclaresmyth.com/wp-content/uploads/2017/07/CORE_Interior_01-1-0x0.jpg", url: "https://www.corebyclaresmyth.com/")
l8 = Activity.create(title: "Ormer Mayfair", description: "Shaun Rankin received a Michelin star in 2005 for his first restaurant in the Channel Islands. He held this for eight years until the launch of his second restaurant in 2013 for which he was awarded a Michelin star just four months after opening. His latest venture at Ormer Mayfair continues this celebration in the accolades it has received since opening. ", category: "Restaurant", image: "https://media-cdn.tripadvisor.com/media/photo-s/0c/ab/17/5d/ormer-mayfair-restaurant.jpg", url: "https://www.flemings-mayfair.co.uk/fine-dining-london/ormer-mayfair-restaurant/?utm_source=mybusiness&utm_medium=organic")
l20 = Activity.create(title: "La Dame de Pic", description: "Offering Anne-Sophie’s signature cuisine, this celebrated French restaurant is located within the majestic setting of Four Seasons Hotel London at Ten Trinity Square, overlooking the Tower of London and
Tower Bridge.", category: "Restaurant", image: "https://media-cdn.tripadvisor.com/media/photo-s/0e/d6/0a/74/la-dame-de-pic-london.jpg", url: "https://www.ladamedepiclondon.co.uk/?seo=google_local_tri5_emea%3Fseo%3Dgoogle_local_tri5_emea")
l10 = Activity.create(title: "Skylon", description: "Skylon is situated on the first floor of the Royal Festival Hall in the Southbank Centre and offers stunning views from huge floor-to-ceiling windows. The restaurant features modern European cuisine in a relaxed atmosphere separated by a stunning centerpiece bar, which is renowned for its fabulous cocktails.", category: "Restaurant", image: "", url: "https://www.skylon-restaurant.co.uk/")
l20 = Activity.create(title: "Southampton Arms", description: "The sign outside announces ‘ale, cider, meat’, and that pretty much sums up what’s on offer at the best pub in Gospel Oak. This utterly unpretentious local loves small-producer ales and ciders .", category: "Pub", image: "https://media.timeout.com/images/131425/750/422/image.jpg", url: "http://www.thesouthamptonarms.co.uk/")
l21 = Activity.create(title: "The Mayflower", description: "Of all the Thamesside pubs, this one is the most special, the most atmospheric, the most tucked-away – and its wooden deck at the back has probably the best view of the river too.", category: "Pub", image: "https://media.timeout.com/images/101673607/750/422/image.jpg", url: "https://www.mayflowerpub.co.uk/")
l22 = Activity.create(title: "Peckham Springs", description: "London’s first co-operatively owned pub, which was saved from closure by locals and now hosts live events most nights of the week.", category: "Pub", image: "https://media.timeout.com/images/101791085/750/422/image.jpg", url: "https://bookings.designmynight.com/book?venue_id=5279282b0a8efb810adbfde7&affiliate_id=577b8462235b15534b8b457c")


Cj0KCQjwwODlBRDuARIsAMy_28Vi5A2iPK5MgKE3XNxVbeZDSBTMxW2ttCDkVwC2FS = Activity.create(title: "The O2", description: "The O2 Arena is a multi-purpose indoor arena located in the centre of The O2 entertainment complex on the Greenwich Peninsula in southeast London", category: "Concert", image: "https://media.headbox.com/uploads/space_photo/filename/30353/detail_Arena2.jpg", url: "https://www.stubhub.co.uk/the-o2-arena-tickets/venue/99499/?&gcid=C12289B333&keyword=cpid-1736224685_agid-70613036329_aud-394096958325:dsa-91726143421_c&creative=336174823424&valueMessaging&gclid=Cj0KCQjwwODlBRDuARIsAMy_28W-zZKsj_ukZjCTLHjAiETRrBNO_kp1Io86L_99MfhwT5nNXlr4n_oaAnKlEALw_wcB&gclsrc=aw.ds")
l26 = Activity.create(title: "The Royal Opera House", description: "The Royal Opera House is an opera house and major performing arts venue in Covent Garden, central London. The large building is often referred to as simply Covent Garden, after a previous use of the site of the opera house's original construction in 1732.", category: "Concert", image: "https://farm6.static.flickr.com/5705/30652828383_d39ed10c92.jpg", url: "https://www.roh.org.uk/events?gclid=Cj0KCQjwwODlBRDuARIsAMy_28UVFmZQs91NehNrr6fPUilwsZjmE8eBsMz_ib7Uv63AYO7a8bXHKHMaAsevEALw_wcB")

l27 = Activity.create(title: "Southbank Centre", description: "Southbank Centre is a complex of artistic venues in London, England, on the South Bank of the River Thames. It comprises three main performance venues, together with the Hayward Gallery, and is Europe’s largest centre for the arts.", category: "Concert", image: "https://d33hx0a45ryfj1.cloudfront.net/additional/Dynamic/media/0B9428B3-3194-4AE3-9AA2A5B8901B3377?w=1600&h=750&crop=1", url: "https://www.southbankcentre.co.uk/whats-on")
l28 = Activity.create(title: "Sofar Sounds", description: "Sofar transforms everyday spaces - like a living room or retail shop - and turns it into a captivating venue for secret, live shows, creating an immersive experience that brings guests and artists closer together. Each Sofar is small, and typically features three diverse acts, with no headliner.", category: "Concert", image: "https://sofarlive.cdn.prismic.io/sofarlive/fff95e3660f0894e0ddcb54e381bd78b485dfbb5_london-shoreditchtreehouse-jane_jimenez.jpg", url: "https://www.sofarsounds.com/london")
l29 = Activity.create(title: "Hoxton Bar and Kitchen", description: "Arty restaurant & bar with a menu of upscale barbecue dishes, live alternative music & DJs.", category: "Concert", image: "https://static.designmynight.com/uploads/2018/04/15799998_1291641394230970_6227650445409789202_o-optimised.jpg", url: "http://www.hoxtonsquarebar.com/events/")

l30 = Activity.create(title: "Genesis Cinema", description: "Arthouse cinema showing blockbuster and independent films in a renovated 19th-century building.", category: "Theatre", image: "https://139060-409135-1-raikfcquaxqncofqfm.stackpathdns.com/wp-content/uploads/2018/10/6J4A0112-1024x683.jpg", url: "https://genesiscinema.co.uk/GenesisCinema.dll/Home")
l31 = Activity.create(title: "National Theatre", description: "The Royal National Theatre in London, commonly known as the National Theatre, is one of the United Kingdom's three most prominent publicly funded performing arts venues, alongside the Royal Shakespeare Company and the Royal Opera House. ", category: "Theatre", image: "https://www.nationaltheatre.org.uk/sites/default/files/promote/EntryPass_TEST_BackstageTours_photo%20by%20Philip%20Vile_1280x720.jpg", url: "https://www.nationaltheatre.org.uk/whats-on")
l32 = Activity.create(title: "Savoy Theatre", description: "The Savoy Theatre is a West End theatre in the Strand in the City of Westminster, London, England. The theatre opened on 10 October 1881 and was built by Richard D'Oyly Carte on the site of the old Savoy Palace.", category: "Theatre", image: "https://resources-cdn.atgtickets.com/static/868_full.png", url: "https://www.boxoffice.co.uk/arts-and-theatre-tickets/musicals/9-to-5-the-musical-tickets.aspx?gclid=Cj0KCQjwwODlBRDuARIsAMy_28Vl9xMhxYuOfhoHNo-mWBkWOl7-naYifxmqgUuQd6gbBG9xXK9Pe9IaAjQSEALw_wcB")
l33 = Activity.create(title: "Shakespeare's Globe", description: "Shakespeare's Globe is the complex housing a reconstruction of the Globe Theatre, an Elizabethan playhouse associated with William Shakespeare, in the London Borough of Southwark, on the south bank of the River Thames. ", category: "Theatre", image: "https://www.daysoutguide.co.uk/media/431763/shakespeares-globe-1.jpg?anchor=center&mode=crop&width=618&height=350&rnd=131768136540000000", url: "https://www.shakespearesglobe.com/?gclid=Cj0KCQjwwODlBRDuARIsAMy_28Vi5A2iPK5MgKE3XNxVbeZDSBTMxW2ttCDkVwC2FS-_qpNaxSxzpXAaAmoMEALw_wcB")
l34 = Activity.create(title: "Barbican", description: "The Barbican Centre is a performing arts centre in the Barbican Estate of the City of London and the largest of its kind in Europe. The Centre hosts classical and contemporary music concerts, theatre performances, film screenings and art exhibitions. It also houses a library, three restaurants, and a conservatory.", category: "Theatre", image: "https://cdn.thestage.co.uk/wp-content/uploads/2016/03/Barbican.jpg", url: "https://www.barbican.org.uk/whats-on/cinema?utm_campaign=CCOCIN250119D&utm_source=WatchThisSpace_AdWords&utm_medium=Adwords&utm_content=CCOCIN250119D_book&gclid=Cj0KCQjwwODlBRDuARIsAMy_28WZOz3W7WwFFW0elZwfRUK-JFUYDUD1Ek1B9ZN_2cf5Qz3LhA1KWLMaAtG-EALw_wcB")



u1 = User.create(name: "Riccardo", email: "ric123@gmail.com", password: "bananasarecool")
u2 = User.create(name: "Myrto", email: "myrtokonst@gmail.com", password: "parampimpom")
u3 = User.create(name: "George", email: "gorgey-boy@gmail.com", password: "ilikebeefjerky")
u4 = User.create(name: "Ranjit", email: "ranpan@gmail.com", password: "ilovebooksiamanerd")

b1 = Booking.create(user_id: User.first.id, activity_id: Activity.first.id)
